import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <nav className="h-12 border-b-gray-800 border-b w-full flex justify-between items-center px-5">
      <h2 className="font-semibold hover:bg-gray-200/20 rounded-md transition-all hover:transition-all duration-300 hover:duration-300  hover:cursor-pointer px-2 py-1">
        HOSTMAN
      </h2>
      <div className="flex gap-4">
        <button   className="text-sm  border-green-300 border bg-emerald-950 text-emerald-300 px-4 rounded-sm hover:bg-emerald-950/20 hover:text-emerald-700 transition-all hover:transition-all">
          Save My Workspace
        </button>
        <button className="bg-red-500 hover:bg-red-700 hover:transition-all transition-all text-white font-semibold px-3 py-1 text-sm rounded-sm">
          Login
        </button>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-neutral-950 overflow-hidden text-white min-h-screen flex flex-col"}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
